name: Main

on:
  push:
    branches:
      - 'main'

jobs:
  # STEP 1: Run Angular e2e tests with Cypress
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        working-directory: ./double-webapp
        uses: cypress-io/github-action@v1

  # STEP 2: Publish to GitHub Packages
#  build:

  # STEP 3: Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./double-webapp
        run: npm i && npm run gh-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: /dist/double-webapp
