name: Main

on:
  push:
    branches:
      - 'main'

jobs:
  # STEP 1: Run Angular e2e tests with Cypress
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@
        # FixMe: need to fix this workflow...

  # STEP 2: Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm i && npm run gh-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./dist/double
